### ISSUE TITLE
加载ArcGIS API for JS中未包含的dojo包

### ISSUE THREAD

**Issue by 180ParkerLi** [biubu/arcgis-vue#29]
我想在vue中使用esri-loader加载ArcGIS API for js中未包含的dojo包，我该怎么做

**Comment by biubu** [comment]
esri-loader本身就是为了摆脱dojo开发的,再者说,你都用vue,为啥还要dojo?

**Comment by 180ParkerLi** [comment]
![image](https://user-images.githubusercontent.com/99329703/227714478-bf263cb8-ea32-46f0-8aef-033cade87f74.png)
在地图上面绘制迁徙图，需要加载扩展的EchartsLayer图层类，而这个是ArcGIS API for js中未包含的dojo包（纯小白）

**Comment by biubu** [comment]
直接用ArcGIS API for js 画不行吗?还是啥意思,没明白.

**Comment by 180ParkerLi** [comment]
我也不太清楚，我只是在看了很多demo他们都是用了这个图层来来绘制迁徙图
![image](https://user-images.githubusercontent.com/99329703/227715863-688bb0d2-8613-4f2a-ae1f-bcc230bf6eec.png)
但是我在vue中使用相同的方式引入，发现并不起作用甚至还报错了

**Comment by biubu** [comment]
你不清楚,我更不清楚,你还是先整明白你要弄啥吧.
